version: '3'

services:
  php:
    build:
      context: .
      dockerfile: build/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/symfony
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    environment:
      SSH_AUTH_SOCK: /ssh-agent
  nginx:
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony

