version: '3'

services:
  php:
    build:
      context: .
      dockerfile: build/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/symfony
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    networks:
      - symfony
  nginx:
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony
    networks:
      - symfony

###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    command: [ '--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - symfony
###< doctrine/doctrine-bundle ###
networks:
  symfony:

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
